import './globals.css';
import type { Metadata } from 'next';
import { Playfair_Display } from 'next/font/google';
import Navbar from './Navbar/Navbar';

const playFairDisplay = Playfair_Display({
  weight: ['400', '500', '700'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={playFairDisplay.className}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
